apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- route.yaml
commonLabels:
  app: alessandro-lumino-node-sample-app
  app.kubernetes.io/instance: alessandro-lumino-node-sample-app
  app.kubernetes.io/name: alessandro-lumino-node-sample-app
